import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import{supabase}from'./lib/supabaseClient';import{initAnalytics,trackEvent}from'./lib/analytics';import'./style.css';
const services=[
{n:'تحليل الأسماء والأرقام',e:'Names & Numerology',d:'تحليل رمزي للاسم، اسم الأم، الأرقام ومسار الحياة.'},
{n:'الخريطة الفلكية',e:'Birth Chart',d:'قراءة فلكية اعتماداً على تاريخ ووقت ومكان الميلاد.'},
{n:'بوصلة العلاقة',e:'Relationship Compass',d:'توافق وديناميكية العلاقة بين شريكين.'},
{n:'التاروت',e:'Tarot',d:'قراءة رمزية لسؤال أو موضوع تختارينه.'},
{n:'تفسير الأحلام',e:'Dream Reading',d:'قراءة رموز الحلم وسياقه بطريقة استبصارية.'},
{n:'قراءة الكف',e:'Palm Reading',d:'طلب قراءة مع إمكانية وصف أو صورة الكف.'},
{n:'قراءة الفنجان',e:'Coffee Reading',d:'طلب قراءة رمزية للفنجان.'},
{n:'الأحجار ورمز الحظ',e:'Stones & Lucky Symbol',d:'اقتراحات رمزية مرتبطة ببياناتك واهتماماتك.'},
{n:'برامج 7 / 14 / 21 يوم',e:'Guided Programs',d:'برامج متابعة شخصية وخطوات يومية.'},
{n:'حلول العلاقات الزوجية',e:'Relationship Guidance',d:'مساحة منظمة لعرض المشكلة وطلب قراءة العلاقة.'}
];
function App(){const[user,setUser]=useState(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[msg,setMsg]=useState(''),[selected,setSelected]=useState(null),[question,setQuestion]=useState(''),[birthDate,setBirthDate]=useState(''),[birthPlace,setBirthPlace]=useState(''),[sending,setSending]=useState(false);
useEffect(()=>{initAnalytics();supabase.auth.getSession().then(({data})=>setUser(data.session?.user||null));const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user||null));return()=>subscription.unsubscribe()},[]);
async function signUp(){setMsg('');const{error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:window.location.href}});if(error)return setMsg(error.message);trackEvent('signup');setMsg('تحققي من بريدك لتأكيد الحساب.');}
async function login(){setMsg('');const{error}=await supabase.auth.signInWithPassword({email,password});if(error)return setMsg(error.message);trackEvent('login');setMsg('تم تسجيل الدخول.');}
async function logout(){await supabase.auth.signOut();setMsg('تم تسجيل الخروج.');}
async function resetPassword(){if(!email)return setMsg('اكتبي بريدك الإلكتروني أولاً.');const{error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:window.location.href});setMsg(error?error.message:'أرسلنا رابط استعادة كلمة المرور إلى بريدك.');}
function openService(s){setSelected(s);setMsg('');trackEvent('service_click',{service_name:s.n});setTimeout(()=>document.querySelector('#service')?.scrollIntoView({behavior:'smooth'}),20)}
async function sendRequest(){if(!user){setMsg('سجّلي الدخول أولاً لإرسال طلب القراءة.');document.querySelector('#account')?.scrollIntoView({behavior:'smooth'});return}if(!selected||!question.trim())return setMsg('اكتبي سؤالك أو تفاصيل طلبك.');setSending(true);const{error}=await supabase.from('reading_requests').insert({user_id:user.id,service_type:selected.n,question:question.trim(),birth_date:birthDate||null,birth_place:birthPlace||null});setSending(false);if(error)return setMsg(error.message);trackEvent('reading_request',{service_name:selected.n});setMsg('وصل طلبك إلى NORANA بنجاح.');setQuestion('');}
return <main dir="rtl"><header><div className="mark">✦</div><h1>NORANA</h1><p>Cosmic Insight · نورانا الكونية</p><nav><a href="#services">الخدمات</a><a href="#account">الحساب</a><a href="#consult">استشارة</a></nav></header>
<section className="hero"><h2>رحلتك نحو فهم أعمق لنفسك وعلاقاتك</h2><p>اختاري الخدمة، افتحي صفحتها، واكتبي طلبك مباشرة.</p><button onClick={()=>{trackEvent('premium_click');document.querySelector('#account').scrollIntoView({behavior:'smooth'})}}>Premium · $1</button></section>
<section id="services"><h2>الخدمات</h2><div className="grid">{services.map(s=><button className="card" key={s.n} onClick={()=>openService(s)}><span>✧</span><b>{s.n}</b><small>{s.e}</small><em>فتح الخدمة ←</em></button>)}</div></section>
{selected&&<section id="service" className="service"><button className="close" onClick={()=>setSelected(null)}>×</button><h2>{selected.n}</h2><p className="en">{selected.e}</p><p>{selected.d}</p><textarea placeholder="اكتبي سؤالك أو تفاصيل طلب القراءة..." value={question} onChange={e=>setQuestion(e.target.value)}/><div className="two"><input type="date" value={birthDate} onChange={e=>setBirthDate(e.target.value)}/><input placeholder="مكان الميلاد (اختياري)" value={birthPlace} onChange={e=>setBirthPlace(e.target.value)}/></div><button onClick={sendRequest} disabled={sending}>{sending?'جاري الإرسال...':'إرسال طلب القراءة'}</button></section>}
<section id="account" className="account"><h2>حساب NORANA</h2>{user?<><p>✓ تم تسجيل الدخول</p><button onClick={logout}>تسجيل الخروج</button></>:<><input type="email" placeholder="البريد الإلكتروني" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="كلمة المرور" value={password} onChange={e=>setPassword(e.target.value)}/><div className="actions"><button onClick={login}>دخول</button><button onClick={signUp}>إنشاء حساب</button><button className="ghost" onClick={resetPassword}>نسيت كلمة المرور</button></div></>}{msg&&<p className="msg">{msg}</p>}</section>
<section id="consult" className="consult"><h2>استشارة سريعة</h2><p>10 دقائق · $5</p><button onClick={()=>{trackEvent('consultation_click');setMsg('تم تسجيل اهتمامك بالاستشارة. سجّلي الدخول لإرسال التفاصيل.');document.querySelector('#account').scrollIntoView({behavior:'smooth'})}}>طلب استشارة</button></section>
<footer><div>© 2026 NORANA · All Rights Reserved.</div><p>Copyright · Terms of Use · Privacy Policy · Security</p><small>المحتوى الروحاني للترفيه والاستبصار الشخصي، وليس نصيحة طبية أو قانونية أو مالية. لا نرسل بياناتك الشخصية إلى Google Analytics.</small></footer></main>}
createRoot(document.getElementById('root')).render(<App/>);